### ISSUE TITLE
As a user, I don't expect an Internal Server Error when posting a declaration through the API

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#24] opened 2024-07-02 17:45 UTC
An example declaration is below with paths partially omitted. Specifically, its the `time_zone_offset` causing the problem. If its an integer, the tasker reports an internal server error resulting from validation (I think):

```
Internal Server Error
Unable to validate project configuration due to internal error.
```

Presumably, there are other YAML parameters that can trigger the same error, but I'm not sure which. Hopefully, fixing it for this will fix it for all.  

Hank

(See VLab ticket 126661 for the discovery of the error.)

==========================

```yml
label: BV Streamflow - Hank Test
observed:
  label: OBS Streamflow
  sources:
  - uri: [omitted]/issue92087/inputs/ABRN1_QME.xml
  variable:
    name: QME
  feature_authority: nws lid
  time_scale:
    function: mean
    period: 24
    unit: hours
  type: observations
predicted:
  label: HEFS Streamflow
  sources:
  - uri: [omitted]/issue126661/clone_uppermotribs_hefs_1985
  variable:
    name: SQIN
  time_scale:
    function: mean
    period: 1
    unit: minutes
  type: ensemble forecasts
  time_zone_offset: 0
  unit: CMS
unit: ft3/s
lead_time_pools:
  period: 24
  frequency: 24
  unit: hours
cross_pair: exact
lead_times:
  minimum: 18
  maximum: 720
  unit: hours
season:
  minimum_day: 1
  minimum_month: 1
  maximum_day: 31
  maximum_month: 12
time_scale:
  function: mean
  period: 24
  unit: hours
pair_frequency:
  period: 24
  unit: hours
rescale_lenience: none
features:
- observed: ABRN1
  predicted: ABRN1
probability_thresholds:
- values:
  - 0.01
  - 0.1
  - 0.5
  - 0.9
  - 0.95
  - 0.99
  - 0.995
  - 0.999
  operator: greater
  apply_to: observed
metrics:
- name: brier score
- name: pearson correlation coefficient
- name: bias fraction
- name: continuous ranked probability score
- name: mean absolute error
- name: mean error
- name: sample size
duration_format: hours
decimal_format: '0.000'
output_formats:
- format: csv2
- format: png
  width: 800
  height: 600
  orientation: lead threshold
- format: netcdf2
```

**Comment by james-d-brown** [comment] 2024-07-02 20:51
This is expected behavior. We use the iso8601 standard for all numeric zone offsets. An integer, as you've declared it here is invalid. The zone offset needs to be one of the explicit zone offset shorthands:

```    /** Time zone shorthands, which are currently CONUS-centric. */
    private static final Map<String, ZoneOffset> SHORTHANDS =
            Map.ofEntries( Map.entry( "UTC", UTC ),
                           Map.entry( "GMT", UTC ),
                           Map.entry( "EDT", M4H ),
                           Map.entry( "EST", M5H ),
                           Map.entry( "CDT", M5H ),
                           Map.entry( "CST", M6H ),
                           Map.entry( "MDT", M6H ),
                           Map.entry( "MST", M7H ),
                           Map.entry( "PDT", M7H ),
                           Map.entry( "PST", M8H ),
                           Map.entry( "AKDT", M8H ),
                           Map.entry( "AKST", M9H ),
                           Map.entry( "HADT", M9H ),
                           Map.entry( "HAST", M10H ),
                           Map.entry( "utc", UTC ),
                           Map.entry( "gmt", UTC ),
                           Map.entry( "edt", M4H ),
                           Map.entry( "est", M5H ),
                           Map.entry( "cdt", M5H ),
                           Map.entry( "cst", M6H ),
                           Map.entry( "mdt", M6H ),
                           Map.entry( "mst", M7H ),
                           Map.entry( "pdt", M7H ),
                           Map.entry( "pst", M8H ),
                           Map.entry( "akdt", M8H ),
                           Map.entry( "akst", M9H ),
                           Map.entry( "hadt", M9H ),
                           Map.entry( "hast", M10H ) );
```

Or a valid numeric offset in iso8601, such as +0000 or -0400. In principle, the software could be lenient about a value like '0', but it isn't right now and probably shouldn't be because adopting a standard is generally a good thing.

**Comment by HankHerr-NOAA** [comment] 2024-07-03 11:11
So the integer or string requirement in the schema does not completely describe the actual requirement for `time_zone_offset`. That makes sense. Thanks.

However, I would think an Internal Server Error, much like an NPE, should never be expected.  It should say something that indicates the `time_zone_offset` is not valid, not a generic error that says nothing about what's wrong in the YAML, and actually gives the impression that something is wrong in the COWRES, not in the declaration. That was certainly my first impression when I saw that error page after clicking **Submit**. 

I think, to resolve this, something better than "Internal Server Error" should be returned. That is, unless its impossible to get a better error description, in which case we just have to live with inadequate messaging and potential questions in the future.

Thanks,

Hank

**Comment by james-d-brown** [comment] 2024-07-03 11:23
Yes, agree. The validation is throwing an exception rather than wrapping an error inside an `EvaluationStatusEvent`. We can fix that, for sure. However, the underlying problem is the declaration.

**Comment by james-d-brown** [comment] 2024-07-03 11:55
Will use this one to test the github workflow.

**Comment by james-d-brown** [comment] 2024-07-03 11:55
Where are the estimation options/records in github? Estimating 2 bananas for this one.

**Comment by HankHerr-NOAA** [comment] 2024-07-03 12:16
A web search seemingly implies it may be available in the project, but not tracked with the ticket.  For example, I found this feature request:

https://github.com/orgs/community/discussions/4360

Maybe the projects view offers something?

Hank

**Comment by epag** [comment] 2024-07-03 12:32
![image](https://github.com/NOAA-OWP/wres/assets/7482743/3074a939-c499-4fd7-8082-d3e81cb2b53a)
![image](https://github.com/NOAA-OWP/wres/assets/7482743/4cb93126-9fb3-4735-a8ff-2e0b12cc1284)

**Comment by james-d-brown** [comment] 2024-07-03 12:34
Thanks!

**Comment by james-d-brown** [comment] 2024-07-03 12:47
Currently unable to push. Getting authentication errors despite following the Cheat Sheet. GitHub account is connected to IDEA. Pushing leads to an authentication error:

`13:41:52.016: [wres] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/issue24:refs/heads/issue24 --set-upstream
remote: Permission to NOAA-OWP/wres.git denied to james-d-brown.`

**Comment by epag** [comment] 2024-07-03 12:55
Hmmmm, ack, ill take a look in a minute here

**Comment by epag** [comment] 2024-07-03 12:59
What method did you use to add a user James?

**Comment by epag** [comment] 2024-07-03 13:05
Hm, I followed the cheat sheet step for step for intellij and it is working fine for me

**Comment by james-d-brown** [comment] 2024-07-03 13:15
Not for me. Got there in the end by additionally adding a token, logging in was not enough. Another frustration is that, unless you upte your global git config to use the github no-reply e-mail, your pushes are going to get (correctly) rejected when your settings prevent exposure of your real e-mail. I think the cheat sheet should include that too because amending a commit is a PITA. Anyway, got it pushed in the end.

**Comment by epag** [comment] 2024-07-03 13:18
> Another frustration is that, unless you update your global git config to use the github no-reply e-mail, your pushes are going to get (correctly) rejected when your settings prevent exposure of your real e-mail. I think the cheat sheet should include that too because amending a commit is a PITA. Anyway, got it pushed in the end.

Is there a way to do this through intellij? Otherwise doing that through the cmd is already the first step in the cheat sheet

**Comment by epag** [comment] 2024-07-03 13:29
> Unsure, but the Cheat Sheet is, in that case, not sufficiently clear about where the pipeline begins because there is a heading marked Initial setup [INTELLIJ], which does not imply that some earlier steps are required (given they have the same title without that qualification).

Ill copy that into the intellij section as well

> Next problem: Cheat Sheet doesn't mention how a committer reviews their own commit in order to merge a PR. Don't want to make a habit of bypassing the protections in place, so Cheat Sheet should be clear about this.

You cannot review your own commit, so we will just bypass that rule. I will make that more clear as well

**Comment by james-d-brown** [comment] 2024-07-03 13:35
OK, sounds good. Cheat Sheet also needs info about disposing of the local/issue branch in intellij, once it has been ditched on the remote.

**Comment by james-d-brown** [comment] 2024-07-03 13:42
Cheat Sheet also unclear about how to view PRs in IDEA using the Pull Requests dialog:

`Could not connect to repository github.com/NOAA-OWP/wres with account github.com/james-d-brown Request response: Access to this site has been restricted. If you believe this is an error, please contact https://support.github.com`

**Comment by epag** [comment] 2024-07-03 13:56
> Cheat Sheet also unclear about how to view PRs in IDEA using the Pull Requests dialog:
> 
> `Could not connect to repository github.com/NOAA-OWP/wres with account github.com/james-d-brown Request response: Access to this site has been restricted. If you believe this is an error, please contact https://support.github.com`

Hm, I am getting the same error there, I am uncertain about this one. I can look into it some. To be honest I didn't even know you could do this in intellij and had just been navigating to github 

> OK, sounds good. Cheat Sheet also needs info about disposing of the local/issue branch in intellij, once it has been ditched on the remote.

Can do

**Comment by james-d-brown** [comment] 2024-07-03 14:09
Added some clarification to the declaration wiki that an ISO8601 number is expected for a zone offset (e.g., '-06:00'), else a zone offset shorthand (e.g., CST)

**Comment by epag** [comment] 2024-07-03 14:23
> Cheat Sheet also unclear about how to view PRs in IDEA using the Pull Requests dialog:
> 
> `Could not connect to repository github.com/NOAA-OWP/wres with account github.com/james-d-brown Request response: Access to this site has been restricted. If you believe this is an error, please contact https://support.github.com`

Looks like we are limited to viewing/creating PRs in github. I followed some thread saying that you needed to update intellij and I got this new error:

![image](https://github.com/NOAA-OWP/wres/assets/7482743/4c87001a-e47f-44cd-82dc-0b3b1b599336)


Looks like how the NOAA org permissions are set up limits how intellij can interact with github.

**Comment by epag** [comment] 2024-07-03 14:25
> OK, sounds good. Cheat Sheet also needs info about disposing of the local/issue branch in intellij, once it has been ditched on the remote.

Updated

**Comment by james-d-brown** [comment] 2024-07-25 11:18
Closing, subject to UAT.

**Closed by james-d-brown** 2024-07-25 11:18 UTC
Labels: bug

**Comment by ArvinEsmailzadeh-NOAA** [comment] 2024-08-27 12:56
Posted the evluation in the description of the ticket and no longer get a Internal server error and rather recieve this message when submitting:

"- Failed to deserialize and fully validate the declaration because it contains errors: please fix the declaration and try again. The cause of the error was: Failed to deserialize a 'time_zone_offset'. Please use a valid offset name, such as 'EST' or a valid ISO 8601 UTC offset, such as '-05:00'. (through reference chain: wres.config.yaml.components.EvaluationDeclaration["predicted"])"

Looks good, passes UAT

Arvin

**Comment by ArvinEsmailzadeh-NOAA** [comment] 2024-08-27 12:59
Posted the above evluation and it completed successfully:

4066925107772591186

Passes UAT

Arvin
