### ISSUE TITLE
As a user, I don't want a NumberFormatException when reading thresholds from wrds

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#246] opened 2024-08-21 14:55 UTC
---

Author Name: **James** (James)
Original Redmine Issue: 86907, https://vlab.noaa.gov/redmine/issues/86907
Original Date: 2021-01-14

---

Given an evaluation that includes thresholds from wrds
When I run that evaluation
Then it should not produce a @NumberFormatException@

See #86904-5

**Comment by epag** [comment] 2024-08-21 14:55
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-01-14T16:26:08Z

---

Evaluation that failed is: https://nwcal-wres-prod.[host]/job/3076795148908965082

**Comment by epag** [comment] 2024-08-21 14:55
---

Original Redmine Comment
Author Name: **Chris** (Chris)
Original Date: 2021-01-14T17:00:16Z

---

I think this is a problem that I encountered with the hydrographer. When the WRDS team refactored it and removed @"None"@ values, they didn't fix their json encoder to spit out @null@ or omit missing thresholds. As a result, it spits out stuff like @"major": ""@, where it was @"major": "None"@ beforehand. I'm not sure if this is the core issue here, but, with the hydrographer, it was trying to parse '' into a double. The code probably just needs to change to avoid the parsing when '' is encountered.

**Comment by epag** [comment] 2024-08-21 14:55
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-01-14T17:21:58Z

---

Sounds like a wrds bug too - I wouldn't expect a named threshold to have an empty string attached to it. So perhaps the best thing here is a more meaningful exception on our end and a bug fix on their end (wrds).

**Comment by james-d-brown** [comment] 2024-09-05 13:44
May not be an issue anymore as the wrds threshold reading was largely overhauled since v5.3, for which this was reported.

To reproduce, sounds like a threshold json from wrds should contain an empty string for a threshold value.

**Comment by james-d-brown** [comment] 2024-09-05 13:54
Indeed, this is no longer an issue. The app has no problem parsing a thresholds json with an empty threshold value string. However, I will note that it does have a problem with `none`. If that was a valid response at some point, it isn't now. Closing.

**Closed by james-d-brown** 2024-09-05 13:54 UTC
Labels: bug
