### ISSUE TITLE
As a user, I would like apply a feature-specific adjustment to data and threshold values in order to account for datum differences

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#36] opened 2024-07-12 13:37 UTC
There may be other contexts in which this is useful, as well. This is from a WRES User Support VLab ticket #132398. The problem was that USGS NWIS was providing data relative to MSL, while the WRDS AHPS forecasts are providing simple river levels. Though the WRDS location service includes zero_datum, it is not being applied in the WRDS RFC forecast service. Its unclear if the WRDS should apply that zero_datum by default or via flag. This ticket, however, is for a work-around that would allow for the offset to be declared by the user on a feature-by-feature basis, and then applied to ingested data for one side of the evaluation as well as thresholds when appropriate (as would be the case here if WRDS thresholds were used).  

Thanks,

Hank

**Comment by james-d-brown** [comment] 2024-08-06 09:23
I expect the cleanest way to include this is inband to the declaration of features. For example, you could optionally declare an `observed_datum` (and/or `predicted_datum` and `baseline_datum`). When non-zero, this would be subtracted from the oriented time-series event values.

```
unit: ft
features:
  - {observed: LGNN5, predicted: LGNN5, baseline: LGNN5, observed_datum: 2.3}
```

By definition, a datum is only relevant when adjusting measurements in the evaluation units, so the unit is the evaluation `unit`.

This would be the manual approach. The preferred way would be to use information inband to the data sources, such as WRDS responses.

For thresholds, I don't think there is any need for manual declaration because, if you are declaring the threshold inband, you can declare it with the correct datum offset. If it's coming from a file source or service, it may be necessary to add a `datum` to the `threshold_sources`, which are declared in threshold `unit`, defaulting back to the evaluation `unit` when undeclared.

```
threshold_sources:
  uri: foo_thresholds.csv
  parameter: stage
  provider: NWS-NRLDB
  rating_provider: NRLDB
  missing_value: -999.0
  feature_name_from: predicted
  datum: 0.70104
  unit: m
``` 

Again, though, the preferred approach would be to use information inband to the threshold sources, such as WRDS responses.

**Comment by james-d-brown** [comment] 2024-08-09 16:43
Actually, the language we want to use is probably `vertical_offset`, which is a numeric offset to apply to the elevation registered in a given datum, rather than `datum`, which is more like a reference name or code to the vertical datum used. In this context, we don't actually care what the datum represents, simply that the elevations needs to be adjusted by a fixed value or `vertical_offset`.

Also, while we try not to be too hierarchical in our declaration language, it is more extensible and cleaner to attach this attribute to each feature/single separately. Indeed, we already allow a `wkt` to be declared separately from a `name`. In other words, this:

```
features:
  - { observed: { name: LGNN5, vertical_offset: 2.3 }, predicted: LGNN5, baseline: LGNN5 }
```

Or, equivalently, in the block style:

```
features:
  - observed:
      name: LGNN5
      vertical_offset: 2.3
    predicted: LGNN5
    baseline: LGNN5
```

**Comment by james-d-brown** [comment] 2024-08-12 09:50
Assigning, starting. Estimating 16 bananas. Whether this makes it into 6.25. idk. Even if we aren't ready to deploy 6.25, I may hold off merging this into main because 6.25 is already too big.

**Comment by james-d-brown** [comment] 2024-08-12 09:52
> Or, equivalently, in the block style:
> 
> ```
> features:
>   - observed:
>       name: LGNN5
>       vertical_offset: 2.3
>     predicted: LGNN5
>     baseline: LGNN5
> ```

On the nomenclature, we could also make this more general and simply call it an `offset`, to be understood as a value to add (or subtract?) to (from) each time-series event value on the designated dataset orientation. That way, it serves the purpose of a datum offset, but could be used (or more easily understood as being useful) in other contexts too.

**Comment by james-d-brown** [comment] 2024-08-14 10:25
**Hank**, when you get a minute, could you provide a self-contained example for vlab ticket 132398 for BGDA2? 

The declaration is there, it just needs the wrds time-series, threshold and location responses. Some of that may be in the ticket, such as the wrds time-series response, although that may be a minimal dataset rather than the actual dataset the user deployed (preferred).

TIA.

**Comment by HankHerr-NOAA** [comment] 2024-08-15 11:28
James:

I'll do my best to get that example to you today, but its a pretty full day. I may not be able to get you the example until Monday.  

Thanks,

Hank

**Comment by james-d-brown** [comment] 2024-08-15 11:29
Thanks!

**Comment by HankHerr-NOAA** [comment] 2024-08-15 15:37
VLab ticket #132398 has the needed data to reproduce the evaluation with declaration shared in that ticket. If you would like for me to share that data in this ticket, let me know.

Hank

**Comment by james-d-brown** [comment] 2024-08-15 15:44
Thanks! Yeah, would make sense to share here too, I think.

**Comment by james-d-brown** [comment] 2024-08-15 15:52
> For thresholds, I don't think there is any need for manual declaration because, if you are declaring the threshold inband, you can declare it with the correct datum offset. If it's coming from a file source or service, it may be necessary to add a `datum` to the `threshold_sources`, which are declared in threshold `unit`, defaulting back to the evaluation `unit` when undeclared.
> 
> ```
> threshold_sources:
>   uri: foo_thresholds.csv
>   parameter: stage
>   provider: NWS-NRLDB
>   rating_provider: NRLDB
>   missing_value: -999.0
>   feature_name_from: predicted
>   datum: 0.70104
>   unit: m
> ```

Actually, this wouldn't work because it would need to be feature-specific, as with the time-series data.

However, I don't think it makes sense to provide a clunky option to declare a feature-specific offset for thresholds or even to add a clunky option to clarify whether the offsets declared within the scope of `features` also apply to thresholds. Afterall, the thresholds could have a different datum offset than each side of data, which could in turn all differ, in principle. 

In this situation (in all situations), it makes sense to convert the time-series data to the threshold datum. In other words, a user declares the offsets w/r to each side of time-series data and not for thresholds, separately.

Naturally, we should eventually support an automatic offset calculation for the data served from the WRDS threshold service, but that is a future activity.

**Comment by HankHerr-NOAA** [comment] 2024-08-15 15:52
Declaration is below, as well as the thresholds. RFC forecast data is attached. It should span the desired period plus a few extra hours on each side.

Hank

======================== Declaration

```yml
label: stage test bgda2-ckta2
observed:
  label: USGS NWIS Stage Observations
  sources:
  - interface: usgs nwis
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
  variable:
    name: '00065'
  feature_authority: usgs site code
  type: observations
predicted:
  label: WRDS AHPS API Stage Forecast
  sources:
  - interface: wrds ahps
    uri: https://nwcal-wrds.[domain]/api/rfc_forecast/v2.0/forecast/stage
  variable:
    name: HG
  feature_authority: nws lid
  type: single valued forecasts
unit: FT
lead_time_pools:
  period: 6
  frequency: 6
  unit: hours
lead_times:
  minimum: 0
  maximum: 72
  unit: hours
reference_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
valid_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
features:
- observed: '15478000'
  predicted: BGDA2
- observed: '15056500'
  predicted: CKTA2
feature_service:
  uri: https://nwcal-wrds.[domain]/api/location/v3.0/metadata
metrics:
- name: sample size
- name: mean absolute error
- name: false alarm ratio
threshold_sources:
- uri: https://nwcal-wrds.[domain]/api/location/v3.0/nws_threshold/
  operator: greater equal
  apply_to: observed
  type: value
  parameter: stage
  provider: NWS-NRLDB
  rating_provider: NRLDB
  feature_name_from: observed
minimum_sample_size: 1
summary_statistics:
  statistics:
  - mean
  dimensions:
  - features
duration_format: days
output_formats:
- format: png
  width: 960
  height: 720
  orientation: lead threshold
```

======================== Thresholds

```json
{
    "_metrics": {
        "threshold_count": 3,
        "total_request_time": 0.10360908508300781
    },
    "_warnings": [],
    "_documentation": {
        "swagger URL": "nwcal-wrds.[domain]/docs/location/v3.0/swagger/" 
    },
    "deployment": {
        "api_url": "https://nwcal-wrds.[domain]/api/location/v3.0/nws_threshold/nws_lid/CKTA2,BGDA2/",
        "stack": "prod",
        "version": "v3.6.0",
        "api_caller": "None" 
    },
    "Non-urgent_issue_reporting_link": "https://vlab.noaa.gov/redmine/projects/wrds-user-support/issues/new?issue[category_id]=2830",
    "data_sources": {
        "metadata_sources": [
            "NWS data: NRLDB - Last updated: 2024-08-13 22:54:57 UTC",
            "USGS data: USGS NWIS - Last updated: 2024-08-13 22:17:52 UTC" 
        ],
        "crosswalk_datasets": {
            "location_nwm_crosswalk_dataset": {
                "location_nwm_crosswalk_dataset_id": "3.0",
                "name": "Location NWM Crosswalk v3.0",
                "description": "Created 20240328. Authoritative 3.0 dataset mapping Locations to NWM Reaches.  Source:\n1) NWM Routelink File v3.0\n2) NHDPlus v2.1+\n3) GID" 
            },
            "nws_usgs_crosswalk_dataset": {
                "nws_usgs_crosswalk_dataset_id": "3.0",
                "name": "NWS Station to USGS Gages 3.0",
                "description": "Created 20240328.  Authoritative 3.0 dataset mapping NWS Stations to USGS Gage.  Source:\n1) AHPS CMS Report\n2) HADS dataset\n3) GID" 
            }
        }
    },
    "value_set": [
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "CKTA2",
                "usgs_site_code": "15056500",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 126.0,
                "action": 125.5,
                "flood": 126.0,
                "minor": 126.0,
                "moderate": 129.0,
                "major": 130.5,
                "record": 128.18
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": 16700.0
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 11402.7,
                "action": 10396.2,
                "flood": 11402.7,
                "minor": 11402.7,
                "moderate": 18758.6,
                "major": 22506.5,
                "record": 16592.21,
                "rating_curve": {
                    "location_id": "CKTA2",
                    "id_type": "NWS Station",
                    "source": "NRLDB",
                    "description": "National Weather Service - National River Location Database",
                    "interpolation_method": null,
                    "interpolation_description": null
                }
            }
        },
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "CKTA2",
                "usgs_site_code": "15056500",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 126.0,
                "action": 125.5,
                "flood": 126.0,
                "minor": 126.0,
                "moderate": 129.0,
                "major": 130.5,
                "record": 128.18
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": 16700.0
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 12328.7,
                "action": 11301.0,
                "flood": 12328.7,
                "minor": 12328.7,
                "moderate": 18944.9,
                "major": 22506.5,
                "record": 17062.57,
                "rating_curve": {
                    "location_id": "15056500",
                    "id_type": "USGS Gage",
                    "source": "USGS Rating Depot",
                    "description": "The EXSA rating curves provided by USGS",
                    "interpolation_method": "logarithmic",
                    "interpolation_description": "logarithmic" 
                }
            }
        },
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "BGDA2",
                "usgs_site_code": "15478000",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 22.0,
                "action": 22.0,
                "flood": 23.0,
                "minor": 23.0,
                "moderate": 25.0,
                "major": 27.0,
                "record": null
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": null
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 63375.7,
                "action": 63375.7,
                "flood": 71816.9,
                "minor": 71816.9,
                "moderate": 90530.4,
                "major": 111737.9,
                "record": null,
                "rating_curve": {
                    "location_id": "BGDA2",
                    "id_type": "NWS Station",
                    "source": "NRLDB",
                    "description": "National Weather Service - National River Location Database",
                    "interpolation_method": null,
                    "interpolation_description": null
                }
            }
        }
    ]
}
[132968_wrds_rfc_forecasts.json.gz](https://github.com/user-attachments/files/16627115/132968_wrds_rfc_forecasts.json.gz)

```

**Comment by HankHerr-NOAA** [comment] 2024-08-15 15:58
Need to fix that comment. Something didn't work right.

**Comment by HankHerr-NOAA** [comment] 2024-08-15 16:00
Oh, I see.

James: Please ignore the last line of the threshold JSON. It appears my attempt to attach a file somehow resulted in that weird text. 

Hank

**Comment by james-d-brown** [comment] 2024-08-16 14:47
Seems to be working locally, both for features and feature groups. For example, declaration like this produces the expected offset in relevant statistics (e.g., mean error):

```
features:
  - { observed: { name: DOSC1, offset: 100 }, predicted: DOSC1 }
```

As does this, which is equivalent declaration for a singleton feature group:

```
feature_groups:
  - name: DOSC1
    features:
      - { observed: { name: DOSC1, offset: 100 }, predicted: DOSC1 }
```

**Comment by james-d-brown** [comment] 2024-08-16 14:47
Going to push progress to a branch.

**Comment by james-d-brown** [comment] 2024-08-16 14:53
Progress in https://github.com/NOAA-OWP/wres/tree/issue36

**Comment by james-d-brown** [comment] 2024-08-16 14:55
Build is currently failing, so I guess that cached dependency has gone, will need to fix.

**Comment by james-d-brown** [comment] 2024-08-16 15:55
Build fixed. More testing of real cases next week.

**Comment by james-d-brown** [comment] 2024-08-19 16:15
Anyway, looks good to me. Putting this on hold we have deployed v6.25. I did note a separate issue with summary statistics whereby extraneous thresholds were appearing that originated from a single feature (when aggregating across features), presumably because the statistics were only present for one feature. I will create a separate ticket for that.

**Comment by james-d-brown** [comment] 2024-08-29 10:47
Back to this one.

**Comment by james-d-brown** [comment] 2024-08-29 11:09
Merging in recent changes.

**Comment by james-d-brown** [comment] 2024-08-29 11:41
Merged in, awaiting build/tests. Will create a PR.

**Closed** 2024-08-29 14:38 UTC
Labels: enhancement

**Comment by HankHerr-NOAA** [comment] 2024-09-16 14:05
Testing this using the original declaration in VLab User Support #132398-18.  I'm doing a before (production) and after (staging) comparison,

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 14:16
I reproduced the issue in both production and staging. I then added the adjustment and tried again in staging:

```yaml
- observed: { name: '15478000', offset: -975 }
  predicted: BGDA2
```

When I look at the output, it appears the same: the output MAE values are still over 950.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 14:22
I can see the unadjusted values in the pairs:

```
...
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-21T20:06:00Z,2023-05-23T06:00:00Z,PT33H54M,981.74,19.3
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-19T21:46:00Z,2023-05-21T06:00:00Z,PT32H14M,981.45,17.8
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-23T15:57:00Z,2023-05-25T00:00:00Z,PT32H3M,981.63,17.1
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-22T21:46:00Z,2023-05-24T06:00:00Z,PT32H14M,981.99,19.1
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-17T21:11:00Z,2023-05-19T06:00:00Z,PT32H49M,980.95,17.6
15478000,15478000-BGDA2,00065,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,2023-05-01T12:00:00Z,2023-11-01T00:00:00Z,PT30H,PT36H,2023-05-18T21:49:00Z,2023-05-20T06:00:00Z,PT32H11M,980.97,17.3
...
```

Let me double check the declaration,

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 14:52
The offset stuff appears to be in the code base, which is not unexpected.  

I'm going to try the file-based evaluation that James used for testing. 

Hank

**Comment by james-d-brown** [comment] 2024-09-16 15:02
If there is an issue w/r to service vs. files, then perhaps the features are being augmented with data service-ey information and a regular comparison between the declared and data-centric features is not producing a match. Matching is feature-based, not feature name based. If so, that is a bug that will need to be fixed when I return. However, unclear what pathway this might be because the file responses should exactly match the web service responses. Even though a feature service is declared here, no requests should be made/needed to that service as the features are all declared explicitly, so it must be related to the features as seen by the data. The perils of attempting to reproduce data services with flat files, perhaps. Wouldn't be the first time.

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:04
Yes, its service vs. files. I probably should have run that test 3 weeks ago. Sigh.

I modified the declaration to simplify it, removing summary stats, thresholds, and only computing mean error and sample size. When using WRDS, the adjustment is not applied and I get mean errors in excess of 950 ft. If I use the 132968 tarball data for the `predicted`, I see MEs around 11 ft.  

Based on James's feedback, I need a new "bug" ticket to be addressed in the next release.  I'll share the declaration I used in that ticket. Creating it now,

Hank

**Comment by james-d-brown** [comment] 2024-09-16 15:07
Well, I don't think we can release, really. This is a feature advertised for the current release and it doesn't work, so...

Would be very bad to release a new feature with a known bug, unless there are absolutely critical fixes in the current release that cannot wait. If the latter, then OK, but the new feature should not be advertised at all until it is fixed.

**Comment by james-d-brown** [comment] 2024-09-16 15:08
Still happens when the `feature_service` is deleted, right?

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:16
The new ticket is created. If we decide to not release, however, is that new ticket needed? 

If I remove `feature_service`, which is unnecessary to the evaluation, the results look fine.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:19
And confirmed again: When I add `feature_service` back in, the offset is not applied and mean error values are in excess of 950 ft.

When I remove `feature_service`, the results look good with mean errors around 11 ft (well, as good as an 11 ft ME can be, I guess).

Let me post that in the other ticket.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:21
If that helps to pinpoint the problem, I'm will to do all of the legwork to fix it if you can point me in the right direction.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:21
I need to eat lunch, but will look at your response when I return.  

Hank

**Comment by james-d-brown** [comment] 2024-09-16 15:30
> And confirmed again: When I add `feature_service` back in, the offset is not applied and mean error values are in excess of 950 ft.
> 
> When I remove `feature_service`, the results look good with mean errors around 11 ft (well, as good as an 11 ft ME can be, I guess).
> 
> Let me post that in the other ticket.
> 
> Hank

Ah, so the feature service is the thing that is augmenting the features, probably with geospatial/coordinate information. That makes more sense, because the WRDS responses should be identical, flat files or otherwise. I had forgotten that we allow the `feature_service` to augment, even when features are explicitly/fully declared. Bottom line, the indexing and comparison of features w/r to offsets will probably need to be performed w/r to feature names only, not the full geometries, but that is TBD.

**Comment by HankHerr-NOAA** [comment] 2024-09-16 15:58
Got it. Thanks,

Hank

**Comment by HankHerr-NOAA** [comment] 2024-09-16 16:07
As stated in the deployment ticket #312, I'm going to continue with 6.26. I've already come so far, might as well see it through.  

Since you said, "don't bother advertising", as opposed to "back out the change", I'm just going to slip this ticket to 6.27. Note that the bug ticket for the issue using WRDS will also be in 6.27. If you'd rather I just reject that ticket and focus on this one, let me know.

Thanks,

Hank

**Comment by epag** [comment] 2024-10-21 16:16
Looks like Hank did UAT in the past on this, is that correct?

**Comment by epag** [comment] 2024-10-21 17:09
Or alternatively, what would be the UAT needed here?

**Comment by james-d-brown** [comment] 2024-10-21 17:27
This ticket was completed, but bugs were discovered subsequently and other tickets opened. Since this ticket is closed, pending UAT, and those other tickets are marked 6.28, I think this should be marked UAT for 6.28 too.

**Comment by epag** [comment] 2024-10-21 17:28
Gotcha, thanks, think we are done with UAT then

**Comment by HankHerr-NOAA** [comment] 2024-12-12 19:12
This passes UAT for 6.28,

Hank
