### ISSUE TITLE
Scenario 510 has failing .svg comparison

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#360] opened 2024-11-15 19:14 UTC
Apparently the scenario 510 test passes or fails depending on the hardware that runs it. We believe this is related to JFreeChart

Benchmark:
![FAKE2_FAKE2_MEAN_ERROR](https://github.com/user-attachments/assets/ff4ac768-2496-412f-be84-a3a8e7e45146)

Generated by Jenkins:
![FAKE2_FAKE2_MEAN_ERROR_created](https://github.com/user-attachments/assets/6b91db74-a9b4-4993-9814-cafc8e754ebe)

Benchmark:
![FAKE2_FAKE2_SAMPLE_SIZE](https://github.com/user-attachments/assets/79565547-b5b6-4adf-904c-96a736257eb8)

Generated by Jenkins:
![FAKE2_FAKE2_SAMPLE_SIZE_created](https://github.com/user-attachments/assets/caa69180-b91b-43ac-92ef-fa6e4e728785)
![Uploading Screenshot 2023-04-26 155714.png…]()

**Comment by HankHerr-NOAA** [comment] 2024-11-15 20:04
FYI... I tried to reproduce the problem on the RHEL 8 owpal-d-ised01 machine, but it matched the benchmarks. Evan described how I can use Jenkins to reproduce it for investigation purposes.

Given the nature of the differences - tick marks on the domain axis differing - only one of those plots will actually match the data. That's presumably the benchmark. We need to confirm that. We also need to see if the PNG looks correct (i.e., does it have the same incorrect tick marks as the SVG?). Finally, what is production producing?

I'll take a brief look on Tuesday or Wednesday of next week. Have a great weekend!

Hank

**Comment by james-d-brown** [comment] 2024-11-15 21:12
Interesting, well that provides a hook to dig into w/r to how tick marks are autogenerated, but it must be a platform dependent "feature". As an aside, we are miles behind w/ `jfreesvg` versions because later versions are not deterministic w/r to the string produced, but that seems to be a separate issue from the one reported here, which is probably not related to `jfreesvg`, rather `jfreechart`.

**Comment by epag** [comment] 2024-11-20 18:13
No, they are from my local build

**Comment by HankHerr-NOAA** [comment] 2024-11-20 19:11
Okay. Thanks. You did send me an example of Jenkins generated SVGs a few minutes ago and I confirmed that the images are the same as your local build and do not match the benchmarks.

I also hopped onto the Jenkins  machine, built WRES, ran scenario510, and obtained the benchmark results.

On the same machine, I grabbed the `-dev` .zip Jenkins built, unzipped it, and run it (confirming the `-dev` revision in the stdout logging) and obtained the benchmark results.

My next test is having Jenkins run scenario510, by itself, to see if it gets the benchmark images.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-20 19:24
Thanks, Evan, for your help working through Jenkins.

When run by itself - just scenario510 - I still get the incorrect SVG output.

**Comment by HankHerr-NOAA** [comment] 2024-11-20 19:37
If I add "  - png" to the end, I can confirm that both the PNG and SVG look the same, and both do NOT match the benchmarks.

**Comment by HankHerr-NOAA** [comment] 2024-11-20 20:41
When I add " - csv" to the end, I obtained the same CSV in both the Jenkins run (where SVG does not match benchmarks) and my local run. I've pasted it below. What is plotted in the SVG and PNG along the domain axis are the midpoints of the reference time pooling windows. From the table below, the first such midpoint is about 3/17 06:30:00 Z.  That matches the benchmark images shared in the OP of this ticket; it does not match the Jenkins generated images (which match the Evan-generated images in the OP). Lastly, note that the PNG images match SVG in all runs I've performed.

Bottom line, in some environments, JFreeChart appears to generate images where the points plotted along the domain axis do not match those output to the legacy CSV format. At this time, I have no idea why, and I don't really have a good way to debug this issue since I can't reproduce it in an environment that would allow me to dig into the code.  Jenkins can't serve that purpose.

I plan to move my scenario510 test to the wres-utility package in Jenkins tomorrow, but, again, I don't think that will be overly useful in debugging. It should be useful in testing a fix, however. I'll return to this ticket tomorrow or Friday,

Hank

=================================

```csv
FEATURE DESCRIPTION,EARLIEST ISSUE TIME,LATEST ISSUE TIME,EARLIEST VALID TIME,LATEST VALID TIME,EARLIEST LEAD TIME IN HOURS [MEAN OVER PAST 3 HOURS],LATEST LEAD TIME IN HOURS [MEAN OVER PAST 3 HOURS],MEAN ERROR All data
FAKE2,2551-03-17T00:00:00Z,2551-03-17T13:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-372.857143
FAKE2,2551-03-17T00:00:00Z,2551-03-17T13:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-443.222222
FAKE2,2551-03-17T07:00:00Z,2551-03-17T20:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-372.857143
FAKE2,2551-03-17T07:00:00Z,2551-03-17T20:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-443.222222
FAKE2,2551-03-17T14:00:00Z,2551-03-18T03:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-395.714286
FAKE2,2551-03-17T14:00:00Z,2551-03-18T03:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-451.333333
FAKE2,2551-03-17T14:00:00Z,2551-03-18T03:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,17,40,-489.333333
FAKE2,2551-03-17T21:00:00Z,2551-03-18T10:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-395.714286
FAKE2,2551-03-17T21:00:00Z,2551-03-18T10:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-451.333333
FAKE2,2551-03-17T21:00:00Z,2551-03-18T10:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,17,40,-489.333333
FAKE2,2551-03-18T04:00:00Z,2551-03-18T17:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-408.222222
FAKE2,2551-03-18T04:00:00Z,2551-03-18T17:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-430.000000
FAKE2,2551-03-18T04:00:00Z,2551-03-18T17:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,0,23,-443.333333
FAKE2,2551-03-18T04:00:00Z,2551-03-18T17:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,17,40,-481.200000
FAKE2,2551-03-18T11:00:00Z,2551-03-19T00:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-404.083333
FAKE2,2551-03-18T11:00:00Z,2551-03-19T00:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,17,40,-430.000000
FAKE2,2551-03-18T11:00:00Z,2551-03-19T00:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,0,23,-442.888889
FAKE2,2551-03-18T11:00:00Z,2551-03-19T00:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,17,40,-490.424242
FAKE2,2551-03-18T18:00:00Z,2551-03-19T07:00:00Z,2551-03-17T00:00:00Z,2551-03-19T08:00:00Z,0,23,-391.666667
FAKE2,2551-03-18T18:00:00Z,2551-03-19T07:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,0,23,-442.800000
FAKE2,2551-03-18T18:00:00Z,2551-03-19T07:00:00Z,2551-03-19T08:00:00Z,2551-03-21T16:00:00Z,17,40,-498.111111
```

**Comment by james-d-brown** [comment] 2024-11-20 21:16
For example, I wonder if overriding the java system property "user.timezone" to use UTC would make a difference.

**Comment by james-d-brown** [comment] 2024-11-20 21:25
Something we could try in code is this:

```
        // Set the date/time format
        DateAxis dateAxis = ( DateAxis ) chart.getXYPlot()
                                              .getDomainAxis();
        dateAxis.setDateFormatOverride( new SimpleDateFormat( "yyyy-MM-dd+HH" ) );
```

-->

```
        // Set the date/time format
        DateAxis dateAxis = ( DateAxis ) chart.getXYPlot()
                                              .getDomainAxis();
        SimpleDateFormat format = new SimpleDateFormat( "yyyy-MM-dd+HH" );
        TimeZone timeZone = TimeZone.getTimeZone("UTC");
        format.setTimeZone( timeZone );
        dateAxis.setDateFormatOverride( format );
```

**Comment by james-d-brown** [comment] 2024-11-21 11:52
Will go ahead and make that change. Worst case scenario, it eliminates a good possibility.

**Comment by james-d-brown** [comment] 2024-11-21 12:04
Is the new jenkins job for the system tests down? Haven't seen any recent notifications, only from the old pathway...

**Comment by james-d-brown** [comment] 2024-11-21 12:06
Ah, just as I post that, one arrived. I guess they are just a bit slower than the old pathway.

**Comment by james-d-brown** [comment] 2024-11-21 12:55
Appears not to have helped, same failure as before.

```
    2024-11-21T12:31:31.927+0000  [Test worker] INFO ScenarioHelper - Asserting that outputs match benchmarks for scenario510...
    2024-11-21T12:31:31.930+0000  [Test worker] WARN ScenarioHelper - A miscellaneous result returned (result code2) for file with name FAKE2_FAKE2_SAMPLE_SIZE.svg
    2024-11-21T12:31:31.932+0000  [Test worker] WARN ScenarioHelper - A miscellaneous result returned (result code2) for file with name FAKE2_FAKE2_MEAN_ERROR.svg
```

**Comment by HankHerr-NOAA** [comment] 2024-11-21 13:12
First, I moved the Jenkins scenario510 to `wres-utility/test-scneario510` and confirmed that it works.

Second, upon closer examining of the plotted image, it does look different than the benchmark (shown in the OP of this ticket), but appears to be the correct data. In this case, it appears that JFreeChart just decided that the first tick would be at 3/17 10Z, not 3/17 6Z:

![FAKE2_FAKE2_MEAN_ERROR](https://github.com/user-attachments/assets/ccf2b0f0-769d-4b23-b083-1beaf3d9b610)

The tick marks appear correctly positioned.

Still haven't resolved why different ticks are drawn, but that's certainty better than plotting wrong data.

**Evan:** You said the images you shared were generated locally. Was that a recent run or from the original report of the problem >1 year ago?  If its an old run, can you run scenario510 again to see if you are still getting the same results?

Thanks,

Hank

**Comment by epag** [comment] 2024-11-21 13:14
That was from the original, let me run that now

**Comment by james-d-brown** [comment] 2024-11-21 13:34
Must be something like that, i.e., a small change in layout affecting tick positions, but we explicitly set the font to Liberation Sans and we also set the size for the various components, so I doubt it is that.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 13:51
Correct. With the time zone change, the tick mark positions, given the times in the labels, line up correctly with the plotted data. Before, they appeared off, which was apparently due to the time zone of the labels.  

What is odd is that the benchmark images look fine, which would seemingly imply that the data and the labels were drawn in UTC. Yet, on some machines including Jenkins, the points appear to be UTC, but the labels were in a different time zone. Why? Where does JFreeChart get the default time zone?

Hank

**Comment by james-d-brown** [comment] 2024-11-21 13:53
Oh, yes, that was the basis for my suspicion. I expect JFreeChart uses the default timezone, which comes from the systemn/OS, unless one is declared, and it wasn't being declared. Benchmarks were created on a system/OS in UTC.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 13:54
This is interesting... Running `date` on the Jenkins vs ISED dev machine:

Jenkins: 

```
[hank.herr@owpal-d-wres01 ~]$ date
Thu Nov 21 08:52:06 EST 2024
```

ISED dev:

```
[hank.herr@owpal-d-ised01 ~]$ date
Thu Nov 21 13:53:12 UTC 2024
```

Hmmm...

Hank

**Comment by james-d-brown** [comment] 2024-11-21 13:54
Could obvs check by examining the JFreeChart code, but 99% certain it will be that. i.e., if fooZone == null, get default time zone.

**Comment by james-d-brown** [comment] 2024-11-21 13:57
> This is interesting... Running `date` on the Jenkins vs ISED dev machine:
> 
> Jenkins:
> 
> ```
> [hank.herr@owpal-d-wres01 ~]$ date
> Thu Nov 21 08:52:06 EST 2024
> ```
> 
> ISED dev:
> 
> ```
> [hank.herr@owpal-d-ised01 ~]$ date
> Thu Nov 21 13:53:12 UTC 2024
> ```
> 
> Hmmm...
> 
> Hank

Yeah, so that makes sense. No idea what the residual connection to tick positions might be, if any. Could be a separate thing, connected to some other system default that bleeds through. Could maybe change the Jenkins machine to UTC, but it would be good to identify the root cause and fix, like the missing explicit time zone.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:00
I wonder if JFreeChart is determining tick marks positions using the default time zone and only incorporating your time zone setting when actually drawing the label. If so, that might (?) explain the different tick mark positions. 

Bottom line, I think we need the system time zone on the Jenkins machine to be set to UTC,

Hank

**Comment by james-d-brown** [comment] 2024-11-21 14:03
Possibly, but that would mean yet another setting missing somewhere, but I doubt it because this is being set on the axis.

Either way, good to check, because then we know and can reverse to test a fix.

**Comment by epag** [comment] 2024-11-21 14:04
Here is the output produced locally when I kicked off a run with a fresh pull (Test is still a failure as expected):

![FAKE2_FAKE2_MEAN_ERROR](https://github.com/user-attachments/assets/29b418f3-ba59-4d00-8df2-15d0685a39e2)
![FAKE2_FAKE2_SAMPLE_SIZE](https://github.com/user-attachments/assets/6141ea73-aff5-42d8-b3ee-131d0d987d78)
[pairs.csv.gz](https://github.com/user-attachments/files/17847042/pairs.csv.gz)

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:09
Thanks, Evan! So you can reliably produce the same output as Jenkins locally. 

The system time zone may not be related, since I ran scenario510 as my user on the Jenkins machine and obtained the correct output (matching the benchmark).

Hank

**Comment by epag** [comment] 2024-11-21 14:18
Locally I have this:

```$  java -version
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)```

**Comment by epag** [comment] 2024-11-21 14:28
That doesn't seem to be it 
![image](https://github.com/user-attachments/assets/f54b620f-66e9-45cb-8e71-34bfaf9afd39)

**Comment by james-d-brown** [comment] 2024-11-21 14:32
Java version shouldn't be important. Pretty sure this will be a default setting that is being taken from the os and should be set explicitly. First thing to check is the system time and, if that makes the test pass, we need to find the relevant setting in code.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:32
If I had a way to regenerate the problem that didn't require pushing code to GitHub, I would try this test:

```java
        // Set the date/time format
        DateAxis dateAxis = ( DateAxis ) chart.getXYPlot()
                                              .getDomainAxis();
        SimpleDateFormat format = new SimpleDateFormat( "yyyy-MM-dd+HH" );
        TimeZone timeZone = TimeZone.getTimeZone( "UTC" );
        format.setTimeZone( timeZone );
        dateAxis.setDateFormatOverride( format );

        //Here is the new line of code...
        dateAxis.setTimeZone(timeZone);
```

The test is to make sure the time zone is set before rendering the chart, and I'm hoping that would do it. I believe the tick marks are identified during rendering.  I doubt this will fix the problem; its just a shot in the dark.

Evan: Is that something you can try locally since you can regenerate the problem easily?

Thanks,

Hank

**Comment by james-d-brown** [comment] 2024-11-21 14:35
You can also try to set the java system property on the host when spinning up the tests, "user.time" - I think I mentioned it above.

**Comment by epag** [comment] 2024-11-21 14:35
> If I had a way to regenerate the problem that didn't require pushing code to GitHub, I would try this test:
> 
> ```java
>         // Set the date/time format
>         DateAxis dateAxis = ( DateAxis ) chart.getXYPlot()
>                                               .getDomainAxis();
>         SimpleDateFormat format = new SimpleDateFormat( "yyyy-MM-dd+HH" );
>         TimeZone timeZone = TimeZone.getTimeZone( "UTC" );
>         format.setTimeZone( timeZone );
>         dateAxis.setDateFormatOverride( format );
> 
>         //Here is the new line of code...
>         dateAxis.setTimeZone(timeZone);
> ```
> 
> The test is to make sure the time zone is set before rendering the chart, and I'm hoping that would do it. I believe the tick marks are identified during rendering. I doubt this will fix the problem; its just a shot in the dark.
> 
> Evan: Is that something you can try locally since you can regenerate the problem easily?
> 
> Thanks,
> 
> Hank

Didnt James already do that? 

https://github.com/NOAA-OWP/wres/pull/364/files

**Comment by james-d-brown** [comment] 2024-11-21 14:36
Evan, I think Hank is speculating about an ordering issue. My commit appears to have helped things - there is no longer a discrepancy in the data being seen/plotted - but there remains an issue with tick positions, a secondary issue. I would try to set the "user.timezone" with a system property override on the jvm as the first step.

**Comment by james-d-brown** [comment] 2024-11-21 14:38
In other words, java will look to the system property before it looks to the os.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:42
I added `-Duser.timezone=UTC` to the system testing command in the Jenkins configuration for `test-scenario510`.  I'm hoping that's the correct syntax. It did not seem to have any impact on the image generated.

Hank

**Comment by james-d-brown** [comment] 2024-11-21 14:43
That is the correct syntax. In that case, the remaining issue is probably unrelated to time zone.

**Comment by james-d-brown** [comment] 2024-11-21 14:45
Just one thing to check, you added it to the right block, yes? The -PtestJvmSystemPropertiesGraphics="..."

**Comment by epag** [comment] 2024-11-21 14:45
What is odd to me is that Hank as his Hank user was able to generate the correct images on the jenkins server with the code that jenkins pulled and built, but then jenkins wasnt able to. 

What would change between the Hank user and the Jenkins user that would cause this? There are setting set on a Jenkins basis, but I can't think of what would cause it

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:46
James: Probably not. Let me try that again,

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 14:49
Interesting. So I tried to use GMT as the setting before moving it to the system testing props, and that triggered this exception:

```
    Caused by: java.lang.IllegalStateException: It is required that the Java system property 'user.timezone' be set to 'UTC', e.g. -Duser.timezone=UTC (found GMT instead).
    	at wres.system.SettingsFactory.validateSystemPropertiesRelatedToDatabase(SettingsFactory.java:588)
    	at wres.system.SettingsFactory.applyDatabaseSystemPropertyOverrides(SettingsFactory.java:494)
    	at wres.system.SettingsFactory.createSettingsFromXml(SettingsFactory.java:58)
    	at wres.system.SettingsFactory.createSettingsFromDefaultXml(SettingsFactory.java:37)
    	at wres.systests.ScenarioHelper.<clinit>(ScenarioHelper.java:65)
```

Looks like we might require UTC for that setting.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 15:01
I have a meeting at 10 and likely won't be able to look at this until later today. At this point, I think we have the code at a point where the image generated is correct in both cases. Even though the tick marks are different in the Jenkins run, their position and label look reasonable. That's good.

I can't help but think that the issue relates to how close the first tick mark label gets to the left edge of the range axis tick mark labels. I believe that is the amount of space allocated to the domain axis tick mark labels. Here it is in the benchmark image with an orange line added to show how close they are:

![github60_tick_mark_position](https://github.com/user-attachments/assets/e5ec6ddb-f4ca-432b-a463-ee2bd589f0b6)

If JFreeChart thinks that label goes beyond its allocated space, it will not use that set of tick marks. I'm guessing that leads to the selection we see in Jenkins.  

I just don't see any differences in the tick marks for either the benchmark or Evan/Jenkins even at a pixel label except for some fuzziness near the middle (using MS Paint and zooming in).  

I wonder if the best way to handle this is to turn off svg checking on 510. We are already checking it in 512 and 003, I think (based on a grep for svg). Is that enough?

Hank

**Comment by james-d-brown** [comment] 2024-11-21 15:03
OK, so back to where we were, the remaining issue is probably not related to the time zone. To be absolutely sure, though, you would need to change the system timezone.

No, changing the purpose of scenario510 would not be great. It is intended to test these graphics and it has flagged an issue, which we've just fixed. If we'd turned it off at the beginning, we wouldn't have found the bug. We just need to find the next bug and fix that too.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 15:55
We'll need to talk this through during the meeting today.  

I want to be able to turn off wres-cron system testing. This inconsistency in JFreeChart is preventing that.

Though you refer to it as a "next bug", the chart that is generated is equally as valid as the benchmark chart, imho. So the question is, how long do we want to delay the wres-cron testing being decommissioned in order to investigate this problem? We can discuss that during the meeting,

Hank

**Comment by james-d-brown** [comment] 2024-11-21 15:59
I would not say equally valid. The benchmark is the benchmark. Implicit in defining a benchmark is that the benchmark is not system/os dependent (unless that is explicitly accounted for and expected, which it isn't). Rather, the software is system dependent. That is a bug. Tracing the bug may not be easy, but it is a bug and we should always aim to fix bugs rather than work around them, otherwise the software eventually becomes Swiss cheese.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 19:43
Looking at JFreeChart code starting with GraphGen... I rewrote large chunks of `DateAxis` to serve my purposes, but I don't know that any changes were due to errors so much as missing capabilities that I wanted and which I couldn't have because my JFreeChart was frozen in time, so I wrote them myself.

Looking for the JFreeChart code, I found this website,

https://www.jfree.org/jfreechart/

It appears that it uses the GNU LPGL license, which Google tells me is not compatible with Apache 2.0. Ugh. Anyway, let me see if I can find the code,

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 19:46
Code is in GitHub. For example:

https://github.com/jfree/jfreechart/blob/master/src/main/java/org/jfree/chart/axis/DateAxis.java

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 19:56
In my overridden `DateAxis` code used in GraphGen, I did find this:

```java

    /**
     * Estimate the maximum width of any tick label. This is copied from DateAxis and calls calculateLargestLineWidth,
     * because the version in DateAxis does not handle multiline labels correctly (I ignores the new-line and treats it
     * as one long string).
     * 
     * @param g2
     * @param unit
     * @return
     */
    private double estimateMaximumTickLabelWidthOverride(final Graphics2D g2, final DateTickUnit unit)
    {
...
```

So I overrode the method used to estimate the maximum tick mark width, but it was because of an inability to handle two-line tick labels (using that old version of JFreeChart).

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 19:57
Its worth noting that both the benchmark and Jenkins version of the chart use a 6-hour time unit for the tick marks. The difference is in what is computed as the first tick mark.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:13
A thought... If you look at the original benchmark with the original Jenkins image in the OP, you'll see that the same tick mark is identified as the minimum: 2551-03-17+06.  For the benchmark, that was 6 UTC, while it Jenkins it was 6 EST. Furthermore, the time unit between ticks is the same in both cases: 6 hours.  

Tick marks are identified for a `DateAxis` by looking at "standard" date/times given the time unit and seeing which first one is larger than the lower bound of for the axis.  With a 6-hour time unit, it makes sense that "standard" times using that would be 0, 6, 12, and 18 hours in whatever time zone is used. Suppose that were in EST, or UTC - 5 hours (I'll use EST as shorthand for that). Would 3/17 0 EST show up on the axis given the domain axis bounds that both the benchmark and Jenkins versions appear to share? No: the minimum for the axis appears to be just under 3/17 6Z, which would be just under 3/17 1 EST.

What I'm saying is that the tick marks are being identified relative to EST, not just labeled in EST (which James fixed). We need to figure out how to force JFreeChart to run entirely in UTC. Apparently `-Duser.timezone` did not do the trick.

Hank

**Comment by james-d-brown** [comment] 2024-11-21 20:27
Right, but that's why I asked you to test the override. I would think that the axis is pertinent here, and the time zone is set on that, but you never know, which is why it made sense to check the override and eliminate the possibility of another component that depends on the time zone. The java system property is the only way a java app can determine the system time, there is no direct call to determine an os setting. So, while it is interesting speculation, I think we've ruled that out.

**Comment by james-d-brown** [comment] 2024-11-21 20:28
In short, the "Apparently -Duser.timezone did not do the trick" is more like, it worked as expected and this isn't the droid we're looking for anymore. I mean, assuming it was set correctly, but I think it was, finally, and you can check that in the logging, which repeats back all system property overrides and other relevant settings.

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:32
Well, I asked Evan to perform an experiment to really, positively rule that out, then. :)

Specifically, I've asked Evan to add the code `dateAxis.setTimeZone(timeZone);`.  That should force the timezone to UTC before it goes through the rendering process regardless of any other settings.

If that fixes the problem, then that would imply my Jenkins experiment did not correctly test "-Duser.timezone=UTC" for the purposes of generating the images. I'm not sure what I could have done wrong, but me screwing up that test would be the implication.  

Hank

**Comment by epag** [comment] 2024-11-21 20:37
> > If I had a way to regenerate the problem that didn't require pushing code to GitHub, I would try this test:
> > ```java
> >         // Set the date/time format
> >         DateAxis dateAxis = ( DateAxis ) chart.getXYPlot()
> >                                               .getDomainAxis();
> >         SimpleDateFormat format = new SimpleDateFormat( "yyyy-MM-dd+HH" );
> >         TimeZone timeZone = TimeZone.getTimeZone( "UTC" );
> >         format.setTimeZone( timeZone );
> >         dateAxis.setDateFormatOverride( format );
> > 
> >         //Here is the new line of code...
> >         dateAxis.setTimeZone(timeZone);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The test is to make sure the time zone is set before rendering the chart, and I'm hoping that would do it. I believe the tick marks are identified during rendering. I doubt this will fix the problem; its just a shot in the dark.
> > Evan: Is that something you can try locally since you can regenerate the problem easily?
> > Thanks,
> > Hank
> 
> Didnt James already do that?
> 
> https://github.com/NOAA-OWP/wres/pull/364/files

Looks like this may have resolved things locally for me 

![FAKE2_FAKE2_MEAN_ERROR](https://github.com/user-attachments/assets/71c725bb-f80c-47ad-b37b-a79cd3ea531c)
![FAKE2_FAKE2_SAMPLE_SIZE](https://github.com/user-attachments/assets/241c06f0-7b4a-4b18-8694-3931fd4ea824)

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:39
Here's the weird part... I'm seeing the UTC setting in the logging in multiple places for the Jenkins run.

Hank

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:45
Evan reported to me that he saw the `user.timezone` setting was UTC in the logging before making the change for his experiment, above. 

It seems clear that something in JFreeChart isn't really playing by the rules, or something that is a byproduct of what we are doing is breaking those rules. Forcing the `DateAxis` time zone to UTC resolves the issue, even though `user.timezone` is UTC in every case. 

I will continue to investigate if it is a known issue that JFreeChart doesn't always follow the `user.timezone` setting. 

Hank

**Comment by epag** [comment] 2024-11-21 20:45
I sent this to Hank, but my logging was reporting I was in UTC before I made this change:

```
Test JVM System Properties: [java.awt.headless:true, user.timezone:UTC, wres.dataDirectory:., wres.databaseHost:localhost, wres.databaseName:wrestest2, wres.database
Port:5432, wres.eventsBrokerAddress:localhost, wres.eventsBrokerPort:5673, wres.externalGraphics:true, wres.externalNumerics:true, wres.startBroker:false, wres.useDa
tabase:true, wres.useSSL:false, wres.username:wres_user, wres.xml:true]

```

However, given that setting the timezone to UTC in the code fixes this for me locally I don't believe that log statement

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:53
I can't find anything in the JFreeChart code base that looks problematic, but admit that I'm not well versed enough in the code to know if I'm looking in the right place.  

So it appears we have a mitigation: Force the time zone for `DateAxis` to be in UTC. However, we don't really understand the cause, given that `user.timezone` appears to be "UTC" in all cases.  Do we want to push the mitigation?

Hank

**Comment by epag** [comment] 2024-11-21 20:56
I say push it if only because it resolves a 2 year long local bug that I have. We don't know if this fixes Jenkins yet

**Comment by HankHerr-NOAA** [comment] 2024-11-21 20:58
There might be value in pushing just to see if it fixes the problem in Jenkins. We can yank it out if we decide on a different approach.

**Comment by epag** [comment] 2024-11-21 21:02
created #366

**Comment by james-d-brown** [comment] 2024-11-21 21:09
It probably makes sense, on reflection, it's just a bit obscure. The formatting of the dates in JFree land is separate from the identification of the ticks. Both need the timezone to be set correctly. Hey ho. But it is surprising that, in the absence of a specific setting, it is not requesting the system default. Perhaps the answer to that is that `TimeZone.getDefault()` and the system property `user.timezone` are two separate things and JFree is asking for the former and not the latter.

**Comment by epag** [comment] 2024-11-21 21:11
Change is in, we shall see in a bit now if it fixes Jenkins

**Comment by HankHerr-NOAA** [comment] 2024-11-21 21:13
> Right, I think we were setting the time zone to UTC anyway because that is needed to work with datetimes from the database correctly, which are not correctly set in UTC - there is a separate ticket for that, 91563 in Redmine.

Got it. That must be why it rejected my attempt to set it to something else before, "GMT".  

> Perhaps the answer to that is that TimeZone.getDefault() and the system property user.timezone are two separate things and JFree is asking for the former and not the latter.

I looked up the `TimeZone` javadoc in my investigation. When calling `getDefault()` you get the cached default, first, and then you get the `user.timezone` followed by other stuff that does not apply in our case. JFreeChart calls that `TimeZone.getDefault()` in `DateAxis`. Unless something set the cached default timezone in `TimeZone` to something other than UTC before JFreeChart got its hands on it, I don't see how it could get a time zone other than "UTC".

There is still something missing here, but I'm not sure how much deeper we should continue to dig.

Hank

**Comment by james-d-brown** [comment] 2024-11-21 21:16
I recall now that we set the `user.timezone` in the `build.gradle` app defaults, both for the main app (build task) and for unit tests (test task). So that is why the logging correctly reports the `user.timezone` and adding this setting makes no difference. In short, I assume `TimeZone.getDefault()` and `user.timezone` are not the same droids.

**Comment by james-d-brown** [comment] 2024-11-21 21:20
> I looked up the `TimeZone` javadoc in my investigation. When calling `getDefault()` you get the cached default, first, and then you get the `user.timezone` followed by other stuff that does not apply in our case. JFreeChart calls that `TimeZone.getDefault()` in `DateAxis`. Unless something set the cached default timezone in `TimeZone` to something other than UTC before JFreeChart got its hands on it, I don't see how it could get a time zone other than "UTC".
> 
> There is still something missing here, but I'm not sure how much deeper we should continue to dig.
> 
> Hank

Interesting, well, I suppose it does indeed depend on what "cached" represents. The main thing we've discovered is that JFreeChart requires the time zone to be set explicitly in two places and that is good enough for this ticket, assuming it passes on the jenkins server, which it will...

**Comment by epag** [comment] 2024-11-21 21:52
Looks like the results are in 
![image](https://github.com/user-attachments/assets/82f8aae4-d07c-4cd1-bb71-16119c302458)

**Comment by HankHerr-NOAA** [comment] 2024-11-22 12:04
I think that means we are done with this ticket, right? Marking this done,

Hank

**Closed** 2024-11-22 12:04 UTC
Labels: bug
